### ISSUE TITLE
Possible incorrect handling of parameters in Esys_LoadExternal

### ISSUE THREAD

**Issue by Superhepper** [tpm2-software/tpm2-pytss#26]
I was trying to write a test for esys load external. But I could not even get the simplest test case to work.

```python
import os
import secrets

from contextlib import ExitStack
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.asymmetric import rsa

from tpm2_pytss.binding import *
from .base_esys import BaseTestESYS

class TestLoadExternal(BaseTestESYS):
    def test_load_public_rsa_key(self):
            # The tpm2-tools equivalent of what this tests is attempting to do is
            # the following:

            # tpm2_loadexternal
            #    --hierarchy=o
            #    --key-algorithm=rsa
            #    --public=public_rsa_key.pem
            #    --key-context=signing_key.ctx
            #    --name=signing_key.name

        # Create the 2048 bit RSA key.
        private_rsa_key = rsa.generate_private_key(
            public_exponent=65537,
            key_size=2048,
            backend=default_backend()
        )
        public_rsa_key = private_rsa_key.public_key()

        with ExitStack() as stack:
            # Create the public part.
            in_public = TPM2B_PUBLIC(
                size=0,
                publicArea=TPMT_PUBLIC(
                    type=TPM2_ALG_RSA, # key-algorithm=rsa
                    nameAlg=TPM2_ALG_SHA256, # hash-algorithm = default = sha256
                    objectAttributes=(
                        TPMA_OBJECT_NODA
                        | TPMA_OBJECT_DECRYPT
                        | TPMA_OBJECT_SIGN_ENCRYPT
                        | TPMA_OBJECT_USERWITHAUTH
                    ),
                    authPolicy=TPM2B_DIGEST(size=0),
                    parameters=TPMU_PUBLIC_PARMS(
                        rsaDetail=TPMS_RSA_PARMS(
                            scheme=TPMT_RSA_SCHEME(
                                scheme=TPM2_ALG_NULL,
                                details=TPMU_ASYM_SCHEME(
                                    anySig=TPMS_SCHEME_HASH(
                                        hashAlg=TPM2_ALG_NULL,
                                    ),
                                ),
                            ),
                            symmetric=TPMT_SYM_DEF_OBJECT(
                                algorithm=TPM2_ALG_NULL,
                                keyBits=TPMU_SYM_KEY_BITS(sym=0),
                                mode=TPMU_SYM_MODE(sym=TPM2_ALG_NULL),
                            ),
                            keyBits=public_rsa_key.key_size, # Number of bits in the key 2048
                            exponent=public_rsa_key.public_numbers().e, # exponent of the key 65537
                        ),
                    ),
                    unique=TPM2B_PUBLIC_KEY_RSA(
                        # public part of rsa key.
                        buffer=public_rsa_key.public_numbers().n.to_bytes(public_rsa_key.key_size // 8, byteorder=sys.byteorder)
                    ),
                ),
            )

            in_public_ptr = stack.enter_context(in_public.ptr())
            object_handle = stack.enter_context(self.esys_ctx.flush_tr())

            self.esys_ctx.LoadExternal(
                ESYS_TR_NONE,
                ESYS_TR_NONE,
                ESYS_TR_NONE,
                None,
                in_public_ptr,
                ESYS_TR_RH_OWNER,
                object_handle
            )

            # Get name from the object_handle and compare it to the public key.
            # If there is a difference throw an exception.
```

When I run this test I get following error message. I run this directly at the device.I have tested this with a key that works for tpm2-tools by using a code that is slightly different and it does not matter the test still fails. So is pytss doing something wierd with my parameters?

**"TPM2 Error tpm:parameter(2):key fields are not compatible with the selected use"**

**Comment by pdxjohnny** [comment]
- The code above doesn't run for me, I think `unique` needs to be `TPMU_PUBLIC_ID(rsa=TPM2B_PUBLIC_KEY_RSA(`

- tpm2-tools looks like it calls `load_public_RSA_from_key` for public keys which calls [BN_bin2bn](https://www.openssl.org/docs/man1.1.0/man3/BN_bin2bn.html), which says `BN_bn2bin() converts the absolute value [of n] into big-endian form`. So I think `byteorder` needs to be `"big"`.

- The only other thing I can think of is [ctypes (open TODO in the README for this)](https://github.com/tpm2-software/tpm2-pytss/blob/d84ab944c2795a27a076caf759ecfb31ab667446/tests/test_esys_auto_session_flags.py#L112-L133) being needed for `objectAttributes`. But adding that doesn't seem to do anything for me.


I started https://github.com/tpm2-software/tpm2-pytss/pull/27/files#diff-62e156bb8781e6742ba673eb78fda50a to track the fix for this.

But I'm getting a different error.

```
ERROR: test_load_public_rsa_key (tests.test_esys_load_external.TestLoadExternal)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/johnsa1/Documents/python/tpm2-pytss/tests/test_esys_load_external.py", line 84, in test_load_public_rsa_key
    object_handle,
  File "/home/johnsa1/Documents/python/tpm2-pytss/tpm2_pytss/context.py", line 62, in wrapper
    return func(self.ctxp, *args, **kwds)
  File "/home/johnsa1/Documents/python/tpm2-pytss/tpm2_pytss/util/swig.py", line 168, in wrapper
    return func(*args, **kwargs)
  File "/home/johnsa1/Documents/python/tpm2-pytss/tpm2_pytss/exceptions.py", line 50, in wrapper
    raise TPM2Error(rc)
tpm2_pytss.exceptions.TPM2Error: tpm:parameter(3):value is out of range or is not correct for the context

----------------------------------------------------------------------
Ran 1 test in 0.088s
```

**Comment by Superhepper** [comment]
1: TPMU_PUBLIC_ID, you are absolutely right it was missing from the code (Had it in my original hack but not in the test.)

2.I have tested it with every every singel byte order and it does not change the error. But yes it shoud be big endian because the specifications says it should.

3.Interessting! didn't even consider this. I was playing around with different attributes but it did not seam to have an effect. But this c-type thing seams like a promising lead.

**Comment by Superhepper** [comment]
Adding ctypes for attributes fixed things with my hack. And that works perfectly.

I will look into why the test is not working properly.

**Comment by tstruk** [comment]
Keep in mind that for LoadExternal the ESYS_TR_RH_OWNER param is only valid for Esys >= v3.0.0, in everything below 3.0.0 it needs to be TPM2_RH_OWNER.

**Comment by pdxjohnny** [comment]
> TPM2_RH_OWNER

Thank you! This fixed it for my test (CI is running using the 2.4.0 TSS release :)
