### ISSUE TITLE
Failed building wheel for tpm2-pytss

### ISSUE THREAD

**Issue by psaintmalo** [tpm2-software/tpm2-pytss#271]
`python3 -m pip install git+https://github.com/tpm2-software/tpm2-pytss.git` errors while installing tpm2-pytss on a Raspberry Pi 4B+ due to failing in building wheel.

**Full Output**
```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting git+https://github.com/tpm2-software/tpm2-pytss.git
  Cloning https://github.com/tpm2-software/tpm2-pytss.git to /tmp/pip-req-build-i1xdy0j1
  Running command git clone --filter=blob:none -q https://github.com/tpm2-software/tpm2-pytss.git /tmp/pip-req-build-i1xdy0j1
  Resolved https://github.com/tpm2-software/tpm2-pytss.git to commit fff53df9e612ceeb91e39522b2f9aca8e0bdd495
  Running command git submodule update --init --recursive -q
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pkgconfig in /usr/local/lib/python3.9/dist-packages (from tpm2-pytss==0.1.10.dev717+gfff53df) (1.5.5)
Requirement already satisfied: cffi>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from tpm2-pytss==0.1.10.dev717+gfff53df) (1.15.0)
Requirement already satisfied: cryptography in /usr/local/lib/python3.9/dist-packages (from tpm2-pytss==0.1.10.dev717+gfff53df) (36.0.0)
Requirement already satisfied: asn1crypto in /usr/local/lib/python3.9/dist-packages (from tpm2-pytss==0.1.10.dev717+gfff53df) (1.4.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/dist-packages (from cffi>=1.0.0->tpm2-pytss==0.1.10.dev717+gfff53df) (2.21)
Building wheels for collected packages: tpm2-pytss
  Building wheel for tpm2-pytss (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.9/dist-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpbpiari69
       cwd: /tmp/pip-req-build-i1xdy0j1
  Complete output (81 lines):
  adding path: /tmp/pip-req-build-i1xdy0j1/scripts
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.9
  creating build/lib.linux-aarch64-3.9/tpm2_pytss
  copying tpm2_pytss/constants.py -> build/lib.linux-aarch64-3.9/tpm2_pytss
  copying tpm2_pytss/types.py -> build/lib.linux-aarch64-3.9/tpm2_pytss
  copying tpm2_pytss/fapi_info.py -> build/lib.linux-aarch64-3.9/tpm2_pytss
  copying tpm2_pytss/__init__.py -> build/lib.linux-aarch64-3.9/tpm2_pytss
  copying tpm2_pytss/TSS2_Exception.py -> build/lib.linux-aarch64-3.9/tpm2_pytss
  copying tpm2_pytss/callbacks.py -> build/lib.linux-aarch64-3.9/tpm2_pytss
  copying tpm2_pytss/FAPI.py -> build/lib.linux-aarch64-3.9/tpm2_pytss
  copying tpm2_pytss/TCTI.py -> build/lib.linux-aarch64-3.9/tpm2_pytss
  copying tpm2_pytss/utils.py -> build/lib.linux-aarch64-3.9/tpm2_pytss
  copying tpm2_pytss/TCTILdr.py -> build/lib.linux-aarch64-3.9/tpm2_pytss
  copying tpm2_pytss/ESAPI.py -> build/lib.linux-aarch64-3.9/tpm2_pytss
  copying tpm2_pytss/tsskey.py -> build/lib.linux-aarch64-3.9/tpm2_pytss
  package init file 'tpm2_pytss/internal/__init__.py' not found (or not a regular file)
  creating build/lib.linux-aarch64-3.9/tpm2_pytss/internal
  copying tpm2_pytss/internal/constants.py -> build/lib.linux-aarch64-3.9/tpm2_pytss/internal
  copying tpm2_pytss/internal/crypto.py -> build/lib.linux-aarch64-3.9/tpm2_pytss/internal
  copying tpm2_pytss/internal/utils.py -> build/lib.linux-aarch64-3.9/tpm2_pytss/internal
  running build_ext
  generating cffi module 'build/temp.linux-aarch64-3.9/tpm2_pytss._libtpm2_pytss.c'
  creating build/temp.linux-aarch64-3.9
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/usr/local/lib/python3.9/dist-packages/setuptools/build_meta.py", line 230, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/usr/local/lib/python3.9/dist-packages/setuptools/build_meta.py", line 215, in _build_with_temp_dir
      self.run_setup()
    File "/usr/local/lib/python3.9/dist-packages/setuptools/build_meta.py", line 158, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 190, in <module>
      setup(
    File "/usr/local/lib/python3.9/dist-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/dist-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.9/dist-packages/cffi/setuptools_ext.py", line 144, in run
      base_class.run(self)
    File "setup.py", line 165, in run
      type_map, element_type_map = self.get_mappings()
    File "setup.py", line 160, in get_mappings
      ast = parser.parse(pdata, "tss2_tpm2_types.h")
    File "/usr/local/lib/python3.9/dist-packages/pycparser/c_parser.py", line 147, in parse
      return self.cparser.parse(
    File "/usr/local/lib/python3.9/dist-packages/pycparser/ply/yacc.py", line 331, in parse
      return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
    File "/usr/local/lib/python3.9/dist-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
      tok = call_errorfunc(self.errorfunc, errtoken, self)
    File "/usr/local/lib/python3.9/dist-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
      r = errorfunc(token)
    File "/usr/local/lib/python3.9/dist-packages/pycparser/c_parser.py", line 1931, in p_error
      self._parse_error(
    File "/usr/local/lib/python3.9/dist-packages/pycparser/plyparser.py", line 67, in _parse_error
      raise ParseError("%s: %s" % (coord, msg))
  pycparser.plyparser.ParseError: /usr/include/arm-linux-gnueabihf/bits/types.h:48:1: before: __extension__
  ----------------------------------------
  ERROR: Failed building wheel for tpm2-pytss
Failed to build tpm2-pytss
ERROR: Could not build wheels for tpm2-pytss, which is required to install pyproject.toml-based projects
```

**Comment by whooo** [comment]
Could you try building from https://github.com/whooo/tpm2-pytss/tree/preprocessor-fix ?
I'm unable to reproduce your issue but it should solve your issue

**Comment by psaintmalo** [comment]
Hi,
It doesn't seem to work, this time I'm getting a different error message (I believe I also got it with the master branch at some point but I'm not sure). I'm not able to fully understand why exactly it is failing in this case.

Not sure if I Im building it incorrectly, I cloned the branch using `git clone -b preprocessor-fix https://github.com/whooo/tpm2-pytss.git` and built it with `sudo python3 -m pip install -e .`

If I try to install without sudo I end up with `PermissionError: [Errno 13] Permission denied: 'libesys.h'`

**Error Log**
```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Obtaining file:///home/pi/Downloads/tpm2-pytss
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: cffi>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from tpm2-pytss==0.0.2.dev818+g5b7582d) (1.15.0)
Requirement already satisfied: asn1crypto in /usr/local/lib/python3.9/dist-packages (from tpm2-pytss==0.0.2.dev818+g5b7582d) (1.4.0)
Requirement already satisfied: cryptography in /usr/local/lib/python3.9/dist-packages (from tpm2-pytss==0.0.2.dev818+g5b7582d) (36.0.0)
Requirement already satisfied: pkgconfig in /usr/local/lib/python3.9/dist-packages (from tpm2-pytss==0.0.2.dev818+g5b7582d) (1.5.5)
Requirement already satisfied: pycparser in /usr/local/lib/python3.9/dist-packages (from cffi>=1.0.0->tpm2-pytss==0.0.2.dev818+g5b7582d) (2.21)
Installing collected packages: tpm2-pytss
  Attempting uninstall: tpm2-pytss
    Found existing installation: tpm2-pytss 0.1.10.dev714+g1599eb8
    Can't uninstall 'tpm2-pytss'. No files were found to uninstall.
  Running setup.py develop for tpm2-pytss
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/pi/Downloads/tpm2-pytss/setup.py'"'"'; __file__='"'"'/home/pi/Downloads/tpm2-pytss/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/pi/Downloads/tpm2-pytss/
    Complete output (66 lines):
    adding path: /home/pi/Downloads/tpm2-pytss/scripts
    running develop
    /usr/local/lib/python3.9/dist-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    /usr/local/lib/python3.9/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running egg_info
    creating tpm2_pytss.egg-info
    writing tpm2_pytss.egg-info/PKG-INFO
    writing dependency_links to tpm2_pytss.egg-info/dependency_links.txt
    writing requirements to tpm2_pytss.egg-info/requires.txt
    writing top-level names to tpm2_pytss.egg-info/top_level.txt
    writing manifest file 'tpm2_pytss.egg-info/SOURCES.txt'
    package init file 'tpm2_pytss/internal/__init__.py' not found (or not a regular file)
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'tpm2_pytss/version'
    warning: no files found matching 'tpm2_pytss/config.json'
    warning: no files found matching '*' under directory 'tpm2_pytss/swig'
    warning: no files found matching '*' under directory 'tests'
    warning: no files found matching '*' under directory 'examples'
    warning: no previously-included files found matching 'tpm2_pytss/internal/type_mapping.py'
    adding license file 'LICENSE'
    writing manifest file 'tpm2_pytss.egg-info/SOURCES.txt'
    running build_ext
    generating cffi module 'build/temp.linux-aarch64-3.9/tpm2_pytss._libtpm2_pytss.c'
    creating build
    creating build/temp.linux-aarch64-3.9
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/pi/Downloads/tpm2-pytss/setup.py", line 192, in <module>
        setup(
      File "/usr/local/lib/python3.9/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.9/dist-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/usr/local/lib/python3.9/dist-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.9/dist-packages/cffi/setuptools_ext.py", line 144, in run
        base_class.run(self)
      File "/home/pi/Downloads/tpm2-pytss/setup.py", line 167, in run
        type_map, element_type_map = self.get_mappings()
      File "/home/pi/Downloads/tpm2-pytss/setup.py", line 162, in get_mappings
        ast = parser.parse(pdata, "tss2_tpm2_types.h")
      File "/usr/local/lib/python3.9/dist-packages/pycparser/c_parser.py", line 147, in parse
        return self.cparser.parse(
      File "/usr/local/lib/python3.9/dist-packages/pycparser/ply/yacc.py", line 331, in parse
        return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
      File "/usr/local/lib/python3.9/dist-packages/pycparser/ply/yacc.py", line 1199, in parseopt_notrack
        tok = call_errorfunc(self.errorfunc, errtoken, self)
      File "/usr/local/lib/python3.9/dist-packages/pycparser/ply/yacc.py", line 193, in call_errorfunc
        r = errorfunc(token)
      File "/usr/local/lib/python3.9/dist-packages/pycparser/c_parser.py", line 1931, in p_error
        self._parse_error(
      File "/usr/local/lib/python3.9/dist-packages/pycparser/plyparser.py", line 67, in _parse_error
        raise ParseError("%s: %s" % (coord, msg))
    pycparser.plyparser.ParseError: /usr/include/arm-linux-gnueabihf/bits/types.h:47:1: before: -
    ----------------------------------------
  ERROR: Can't roll back tpm2-pytss; was not uninstalled
ERROR: Command errored out with exit status 1: /usr/bin/python3 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/pi/Downloads/tpm2-pytss/setup.py'"'"'; __file__='"'"'/home/pi/Downloads/tpm2-pytss/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
```

**Comment by whooo** [comment]
Could you upload /usr/include/arm-linux-gnueabihf/bits/types.h somewhere so I could have a look, that or tell me which distribution you are running?

**Comment by psaintmalo** [comment]
Here you go: https://pastebin.com/ffB7Vpg9
I'm running Raspberry Pi OS Lite.

**Comment by whooo** [comment]
could you pull from my branch again and see if it works? I amended the commit..

**Comment by psaintmalo** [comment]
Looks like a different error caused by the same line:
`pycparser.plyparser.ParseError: /usr/include/arm-linux-gnueabihf/bits/types.h:47:1: before: 1`

**Comment by whooo** [comment]
seems to something with the behavior of cpp, could you run cpp --version and provide me with the output?
Also, can you run  `cpp -D__extension__  "-D__attribute__(x)" /path/to/your/tss2_tpm2_types.h` and send me the output?

**Comment by psaintmalo** [comment]
```
# cpp --version
cpp (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110
```

Here is the output from the second command: https://pastebin.com/pc2sTcZx

**Comment by whooo** [comment]
Could you do pull from my branch and test again?

**Comment by psaintmalo** [comment]
Install goes through with no errors and so far works without any problem, thanks!

**Comment by whooo** [comment]
I'll do a PR in a moment, just need to add another fix
