### ISSUE TITLE
pip install fails when installing from source

### ISSUE THREAD

**Issue by abinpaul1** [tpm2-software/tpm2-pytss#277]
I downloaded the source code for pytss from Github (NOT `git clone`).  I attempted running `python setup.py install` to install the same. However I get the following error. When I do `pip install git+https://github.com/tpm2-software/tpm2-pytss.git` it does get installed. Ideally shouldn't it be possible to install with only the source code?
```python3
Traceback (most recent call last):
  File "setup.py", line 192, in <module>
    setup(
  File "/home/abinpaul/Desktop/tpm-pytss/venv_pytss/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/home/abinpaul/Desktop/tpm-pytss/venv_pytss/lib/python3.8/site-packages/setuptools/dist.py", line 453, in __init__
    _Distribution.__init__(
  File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/home/abinpaul/Desktop/tpm-pytss/venv_pytss/lib/python3.8/site-packages/setuptools/dist.py", line 831, in finalize_options
    ep(self)
  File "/home/abinpaul/Desktop/tpm-pytss/venv_pytss/lib/python3.8/site-packages/setuptools_scm/integration.py", line 94, in infer_version
    dist.metadata.version = _get_version(config)
  File "/home/abinpaul/Desktop/tpm-pytss/venv_pytss/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 177, in _get_version
    parsed_version = _do_parse(config)
  File "/home/abinpaul/Desktop/tpm-pytss/venv_pytss/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 135, in _do_parse
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for '/home/abinpaul/Desktop/tpm-pytss/tpm2-pytss-master'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

**Comment by whooo** [comment]
As the version is generated from the git history (which isn't included in master.zip) you need to override it.
Adding a file called PKG-INFO with the content:
```
Metadata-Version: 1.1
Name: tpm2-pytss
Version: 0.1.10
``` 
Should work, just use reasonable values

**Comment by williamcroberts** [comment]
Yeah don't do that, use git or a release from PyPi. Which now RC0 just landed on pypi is easy:
  - pip install tpm2-pytss==1.0.0rc0

I wish I could turn off those auto-generated downloads.

**Comment by abinpaul1** [comment]
Yes,  that's great to know. Congrats guys  🎉
