### ISSUE TITLE
SWIG 4 support

### ISSUE THREAD

**Issue by diabonas** [tpm2-software/tpm2-pytss#4]
When building this project with SWIG 4 (version 4.0.1-1 on Arch Linux), running the tests fails with
```
  File "/home/jonas/tpm2-software/tpm2-pytss/tpm2_pytss/exceptions.py", line 8, in <module>
    from . import esys_binding
  File "/home/jonas/tpm2-software/tpm2-pytss/tpm2_pytss/esys_binding.py", line 413, in <module>
    class TPMS_TAGGED_PROPERTY(object):
  File "/home/jonas/tpm2-software/tpm2-pytss/tpm2_pytss/esys_binding.py", line 417, in TPMS_TAGGED_PROPERTY
    value = property(_esys_binding.TPMS_TAGGED_PROPERTY_value_get, _esys_binding.TPMS_TAGGED_PROPERTY_value_set)
TypeError: 'property' object is not callable
```
This might actually be a bug in SWIG since it seems to overwrite its internal `property()` function with the class attribute `property`:
```python
class TPMS_TAGGED_PROPERTY(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    property = property(_esys_binding.TPMS_TAGGED_PROPERTY_property_get, _esys_binding.TPMS_TAGGED_PROPERTY_property_set)
    value = property(_esys_binding.TPMS_TAGGED_PROPERTY_value_get, _esys_binding.TPMS_TAGGED_PROPERTY_value_set)
```
But even if the autogenerated `esys_binding.py` file is fixed manually, there are lots of other errors, e.g.
```
======================================================================
ERROR: test_audit (tests.test_esys_audit.TestAudit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jonas/tpm2-software/tpm2-pytss/tests/base_esys.py", line 28, in setUp
    self.tcti_ctx = self.ctx_stack.enter_context(self.tcti(config=self.tcti_config))
  File "/usr/lib/python3.7/contextlib.py", line 427, in enter_context
    result = _cm_type.__enter__(cm)
  File "/home/jonas/tpm2-software/tpm2-pytss/tpm2_pytss/tcti.py", line 34, in __enter__
    ctxpp.__enter__()
  File "/home/jonas/tpm2-software/tpm2-pytss/tpm2_pytss/util/swig.py", line 162, in __enter__
    self.ptr = self._new()
TypeError: new_tcti_ctx_ptr_ptr() takes 0 positional arguments but 1 was given
```
The reason for this error seems to be that in SWIG 3, `new_tcti_ctx_ptr_ptr` is defined as
```python
def new_tcti_ctx_ptr_ptr() -> "struct TSS2_TCTI_CONTEXT **":
    return _esys_binding.new_tcti_ctx_ptr_ptr()
new_tcti_ctx_ptr_ptr = _esys_binding.new_tcti_ctx_ptr_ptr
```
while in SWIG 4 the last line is missing. I guess [`tpm2_pytss/util/swig.py`](https://github.com/tpm2-software/tpm2-pytss/blob/master/tpm2_pytss/util/swig.py) needs to be adapted to work with SWIG 4.

Installing the legacy version swig3 and adding `self.swig = "swig-3"` before [`super().run()`](https://github.com/tpm2-software/tpm2-pytss/blob/6065a0321c13d666f918abf1ba3380ecbcad68d5/setup.py#L107) in `setup.py` causes the test suite to run successfully on Arch Linux.

**Comment by pdxjohnny** [comment]
Good catch! thank you!
