### ISSUE TITLE
FAPI drop hardcoded callbacks

### ISSUE THREAD

**Issue by williamcroberts** [tpm2-software/tpm2-pytss#473]
Just create a single C python callback and multiplex to per-fapi context user callbacks similar to PyTCTI or the policy callbacks.

**Comment by williamcroberts** [comment]
Just to be clear this also fixes the hardcoded limitation on the amount of FAPI callabacks that can be set

```python3
#!/usr/bin/env python3

from tpm2_pytss import *

def branch_callback(path, description, branch_names, user_data):
    pass

fl = []
for i in range(0, 20):
    print(i)
    f = FAPI()
    fl.append(f)
    f.set_branch_callback(callback=branch_callback, user_data=b"123456")
```

```bash
./dotest.py 
0
1
2
3
4
5
6
7
8
9
10
Traceback (most recent call last):
  File "./dotest.py", line 13, in <module>
    f.set_branch_callback(callback=branch_callback, user_data=b"123456")
  File "/home/wcrobert/workspace/tpm2-pytss/src/tpm2_pytss/FAPI.py", line 1264, in set_branch_callback
    c_callback = self._register_callback(
  File "/home/wcrobert/workspace/tpm2-pytss/src/tpm2_pytss/FAPI.py", line 1157, in _register_callback
    self.callbacks[callback_type] = get_callback(callback_type)
  File "/home/wcrobert/workspace/tpm2-pytss/src/tpm2_pytss/callbacks.py", line 39, in get_callback
    callback = next(cb for cb in callbacks[callback_type] if cb.free)
StopIteration
```
