### ISSUE TITLE
Can't build a project for Rosa Linux

### ISSUE THREAD

**Issue by betcher** [tpm2-software/tpm2-pytss#482]
Hi. I'am trying to make this project for Rosa Linux.
python3 setup.py build_ext
fails with:

sh-5.1# python setup.py build_ext 
adding path: /var/lib/notamock/BUILD/BUILD/tpm2-pytss-2.0.0/scripts
running build_ext
generating cffi module 'build/temp.linux-x86_64-3.8/tpm2_pytss._libtpm2_pytss.c'
already up-to-date
Traceback (most recent call last):
  File "setup.py", line 280, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib64/python3.8/site-packages/cffi/setuptools_ext.py", line 144, in run
    base_class.run(self)
  File "setup.py", line 230, in run
    type_map, element_type_map = self.get_mappings()
  File "setup.py", line 191, in get_mappings
    tm = self.get_types(ast)
  File "setup.py", line 91, in get_types
    for v in ast:
TypeError: 'FileAST' object is not iterable

How can i fix it?

**Comment by whooo** [comment]
Could you run: pip show pycparser and include the output?

**Comment by betcher** [comment]
sh-5.1# pip3 show pycparser
Name: pycparser
Version: 2.10
Summary: C parser in Python
Home-page: https://github.com/eliben/pycparser
Author: Eli Bendersky
Author-email: eliben@gmail.com
License: BSD
Location: /usr/lib/python3.8/site-packages
Requires: 
Required-by: cffi

**Comment by betcher** [comment]
You answered unexpectedly quickly )

**Comment by whooo** [comment]
could you try installing a newer version of pycparser? My system uses 2.21 which works

**Comment by betcher** [comment]
Thanks!!! It works!
