### ISSUE TITLE
1.9.0: issue with `tpm2_pytss` python module detection

### ISSUE THREAD

**Issue by kloczek** [tpm2-software/tpm2-pytss#496]
Something is wrong with `tpm2_pytss` module detection.
```console
checking whether /usr/bin/python3 version is >= 3.7... yes
checking for /usr/bin/python3 version... 3.8
checking for /usr/bin/python3 platform... linux
checking for GNU default /usr/bin/python3 prefix... ${prefix}
checking for GNU default /usr/bin/python3 exec_prefix... ${exec_prefix}
checking for /usr/bin/python3 script directory (pythondir)... ${PYTHON_PREFIX}/lib/python3.8/site-packages
checking for /usr/bin/python3 extension module directory (pyexecdir)... ${PYTHON_EXEC_PREFIX}/lib64/python3.8/site-packages
checking for module pyasn1_modules in python... found
checking for module pyasn1 in python... found
checking for module cryptography in python... found
checking for module yaml in python... found
checking for module tpm2_pytss in python... configure: error: not found
```
In config.log I see only
```console
configure:14390: checking whether /usr/bin/python3 version is >= 3.7
configure:14401: /usr/bin/python3 -c import sys # split strings by '.' and convert to numeric. Append some zeros # because we need at least 4 digits for the hex conversion. # map returns an
 iterator in Python 3.0 and a list in 2.x minver = list(map(int, '3.7'.split('.'))) + [0, 0, 0] minverhex = 0 # xrange is not present in Python 3.0 and range returns an iterator for i in li
st(range(0, 4)): minverhex = (minverhex << 8) + minver[i] sys.exit(sys.hexversion < minverhex)
configure:14404: $? = 0
configure:14407: result: yes
configure:14507: checking for /usr/bin/python3 version
configure:14515: result: 3.8
configure:14520: checking for /usr/bin/python3 platform
configure:14528: result: linux
configure:14589: checking for GNU default /usr/bin/python3 prefix
configure:14591: result: ${prefix}
configure:14657: checking for GNU default /usr/bin/python3 exec_prefix
configure:14659: result: ${exec_prefix}
configure:14690: checking for /usr/bin/python3 script directory (pythondir)
configure:14725: result: ${PYTHON_PREFIX}/lib/python3.8/site-packages
configure:14733: checking for /usr/bin/python3 extension module directory (pyexecdir)
configure:14768: result: ${PYTHON_EXEC_PREFIX}/lib64/python3.8/site-packages
configure:14781: checking for module pyasn1_modules in python
configure:14787: result: found
configure:14791: checking for module pyasn1 in python
configure:14797: result: found
configure:14801: checking for module cryptography in python
configure:14807: result: found
configure:14811: checking for module yaml in python
configure:14817: result: found
configure:14821: checking for module tpm2_pytss in python
configure:14825: error: not found
```
pop shows
```console
[tkloczko@pers-jacek SPECS]$ pip show tpm2_pytss
Name: tpm2-pytss
Version: 1.1.0
Summary: TPM 2.0 TSS Bindings for Python
Home-page: https://github.com/tpm2-software/tpm2-pytss
Author: William Roberts
Author-email: william.c.roberts@intel.com
License: BSD
Location: /usr/lib64/python3.8/site-packages
Requires: asn1crypto, cffi, cryptography, packaging, pyyaml
Required-by:
```

**Comment by whooo** [comment]
I need more context, we don't use autoconf for the bindings so it seems to be related to another project.

**Comment by aplanas** [comment]
I guess that the original bug is referred to when compiling "tpm2-pkcs11", as indeed the last version when using "tpm2-pytss" 2.0.0 generates this error, but I managed to make it work when updating to 2.1.0.

"configure" does a simple test, it try "import tpm2_pytss", and indeed it fails in the old pytss version here:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.10/site-packages/tpm2_pytss/__init__.py", line 2, in <module>
    from .ESAPI import ESAPI
  File "/usr/lib64/python3.10/site-packages/tpm2_pytss/ESAPI.py", line 2, in <module>
    from .types import *
  File "/usr/lib64/python3.10/site-packages/tpm2_pytss/types.py", line 12, in <module>
    from ._libtpm2_pytss import ffi, lib
ImportError: /usr/lib64/python3.10/site-packages/tpm2_pytss/_libtpm2_pytss.abi3.so: undefined symbol: Tss2_MU_TPMS_ALGORITHM_DESCRIPTION_Marshal
```

Again, moving to 2.1.0 seems to fix the issue.

**Comment by kloczek** [comment]
Sorry I was busy a bit ..
Just tested and after upgarde `tpm2-pytss` module to 2.1.0 tpm2-pkcs11 is passing autoconf correctly.
Thank you 👍 
And closing.
