### ISSUE TITLE
rewrite: Cython

### ISSUE THREAD

**Issue by pdxjohnny** [tpm2-software/tpm2-pytss#50]
Exploring cython as an alternative to SWIG

**Comment by pdxjohnny** [comment]
Cython has an issue where it can't do VLA's: https://github.com/cython/cython/issues/1305

This results in issue with the way many of the `TPMX_*` structs are defined:

```python
TPM2_MAX_AC_CAPABILITIES = (TPM2_MAX_CAP_BUFFER / sizeof(TPMS_AC_OUTPUT))

cdef extern from "<tss2/tss2_tpm2_types.h>":
    # Definition of TPML_AC_CAPABILITIES Structure <OUT> 
    struct TPML_AC_CAPABILITIES:
        UINT32 count # Number of values in the acCapabilities list. May be 0
        TPMS_AC_OUTPUT acCapabilities[TPM2_MAX_AC_CAPABILITIES] # List of AC values
```

```
[1/1] Cythonizing /home/pdxjohnny/Documents/python/cython-pytss/tpm2_pytss/tss2_tpm2_types.pyx

Error compiling Cython file:
------------------------------------------------------------
...

cdef extern from "<tss2/tss2_tpm2_types.h>":
    # Definition of TPML_AC_CAPABILITIES Structure <OUT>
    struct TPML_AC_CAPABILITIES:
        UINT32 count # Number of values in the acCapabilities list. May be 0
        TPMS_AC_OUTPUT acCapabilities[TPM2_MAX_AC_CAPABILITIES] # List of AC values
                                     ^
------------------------------------------------------------

tpm2_pytss/tss2_tpm2_types.pyx:16:38: Not allowed in a constant expression

Error compiling Cython file:
------------------------------------------------------------
...

cdef extern from "<tss2/tss2_tpm2_types.h>":
    # Definition of TPML_AC_CAPABILITIES Structure <OUT>
    struct TPML_AC_CAPABILITIES:
        UINT32 count # Number of values in the acCapabilities list. May be 0
        TPMS_AC_OUTPUT acCapabilities[TPM2_MAX_AC_CAPABILITIES] # List of AC values
                                     ^
------------------------------------------------------------

tpm2_pytss/tss2_tpm2_types.pyx:16:38: Array dimension not integer

Error compiling Cython file:
------------------------------------------------------------
...

cdef extern from "<tss2/tss2_tpm2_types.h>":
    # Definition of TPML_AC_CAPABILITIES Structure <OUT>
    struct TPML_AC_CAPABILITIES:
        UINT32 count # Number of values in the acCapabilities list. May be 0
        TPMS_AC_OUTPUT acCapabilities[TPM2_MAX_AC_CAPABILITIES] # List of AC values
                                    ^
------------------------------------------------------------

tpm2_pytss/tss2_tpm2_types.pyx:16:37: Variable type 'TPMS_AC_OUTPUT []' is incomplete
Traceback (most recent call last):
  File "setup.py", line 82, in <module>
    compiler_directives={"language_level": "3"},
  File "/home/pdxjohnny/.pyenv/versions/3.7.6/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1102, in cythonize
    cythonize_one(*args)
  File "/home/pdxjohnny/.pyenv/versions/3.7.6/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 1225, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /home/pdxjohnny/Documents/python/cython-pytss/tpm2_pytss/tss2_tpm2_types.pyx
```

**Comment by pdxjohnny** [comment]
As far as I can tell this ends up being a show stopper for Cython usage. Since those `sizeof`s are platform dependent and not something we can calculate ahead of time and put in static values for.

**Comment by williamcroberts** [comment]
I thought you we're going to write a parser that generates all of the boring parts. Couldn't it just write a little program and execute it to get the system size during build time?
```C
#include <stdio.h>

int main(int argc, char *argv[]) {
        printf("%zu\n", sizeof(SIZEOF_TYPE));
        return 0;
}
```
```bash
gcc -o sizeofprog -D'SIZEOF_TYPE=int' sizeof_prog.c
./sizeofprog
4
```

A simple way if you're doing it by hand would be to just drop that in via a placeholder? You could probably just markup the CYTHON with something like
__SIZEOF_MYTYPE__ and then sed -i it with the value from the little program.

So you just need to add a little build time preprocessing.

An alternative would be to use autoconf's AC_CHECK_SIZEOF. So generate that with the unknown types and then pass them via a generated python file. That macro would create things like SIZEOF_INT_P, which you could output to the config.h and then sed from that.

**Comment by pdxjohnny** [comment]
https://github.com/pdxjohnny/tpm2-pytss/tree/rewrite

**Comment by williamcroberts** [comment]
Went with CFFI, started.
