### ISSUE TITLE
Runtime Error: Require tss2-esapi to be installed and atleast version 2.4.0

### ISSUE THREAD

**Issue by tabz11** [tpm2-software/tpm2-pytss#502]
Hi,

I am trying to install tpm2_pytss on ubuntu 20.04. I have installed tpm2-tss as per the instructions from [here](https://github.com/tpm2-software/tpm2-tss/blob/master/INSTALL.md). Precisely as follows:

`sudo git clone https://github.com/tpm2-software/tpm2-tss.git `
`sudo ./bootstrap`
`sudo ./configure  --with-udevrulesdir=/etc/udev/rules.d`

But I am getting the following error, while installing `tpm2-pytss`:
`ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /tmp/tmpf48w6sjl prepare_metadata_for_build_wheel /tmp/tmpv_19rx4e
         cwd: /tmp/pip-install-0sr9hs0z/tpm2-pytss
    Complete output (33 lines):
    Traceback (most recent call last):
      File "/tmp/tmpf48w6sjl", line 280, in <module>
        main()
      File "/tmp/tmpf48w6sjl", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmpf48w6sjl", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/tmp/pip-build-env-144aa81v/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/tmp/pip-build-env-144aa81v/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
        exec(code, locals())
      File "<string>", line 280, in <module>
      File "/tmp/pip-build-env-144aa81v/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
        return distutils.core.setup(**attrs)
      File "/tmp/pip-build-env-144aa81v/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 147, in setup
        _setup_distribution = dist = klass(attrs)
      File "/tmp/pip-build-env-144aa81v/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 488, in __init__
        _Distribution.__init__(
      File "/tmp/pip-build-env-144aa81v/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
        self.finalize_options()
      File "/tmp/pip-build-env-144aa81v/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 912, in finalize_options
        ep(self)
      File "/tmp/pip-build-env-144aa81v/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 932, in _finalize_setup_keywords
        ep.load()(self, ep.name, value)
      File "/usr/local/lib/python3.8/dist-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
        add_cffi_module(dist, cffi_module)
      File "/usr/local/lib/python3.8/dist-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
        execfile(build_file_name, mod_vars)
      File "/usr/local/lib/python3.8/dist-packages/cffi/setuptools_ext.py", line 25, in execfile
        exec(code, glob, glob)
      File "scripts/libtss2_build.py", line 13, in <module>
        raise RuntimeError("Require tss2-esapi to be installed and at least version 2.4.0")
    RuntimeError: Require tss2-esapi to be installed and at least version 2.4.0
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpf48w6sjl prepare_metadata_for_build_wheel /tmp/tmpv_19rx4e Check the logs for full command output.
`

Please help!

**Comment by whooo** [comment]
Can you run pkg-config --modversion tss2-esys and provide me with the output?

**Comment by tabz11** [comment]
Thanks, when typing ..
`sudo pkg-config --modversion tss2-esys`

following response: 
`Package tss2-esys was not found in the pkg-config search path.
Perhaps you should add the directory containing `tss2-esys.pc'
to the PKG_CONFIG_PATH environment variable
No package 'tss2-esys' found`

**Comment by whooo** [comment]
Doesn't seem that you have tpm2-tss installed, did you do a make install?

**Comment by tabz11** [comment]
thanks, just did `sudo make install ` and it worked! Thanks
