### ISSUE TITLE
metadata-generation-failed

### ISSUE THREAD

**Issue by rutujakawade** [tpm2-software/tpm2-pytss#516]
When I am trying to install tpm2 on a tpm enable physical host, rocky linux 9.2 using pip install tpm2-pytss

This is the error encountered. 

`pip install tpm2-pytss
Collecting tpm2-pytss
  Using cached tpm2-pytss-2.1.0.tar.gz (203 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-4aog311c/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 380, in prepare_metadata_for_build_wheel
          self.run_setup()
        File "/tmp/pip-build-env-4aog311c/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 280, in <module>
        File "/tmp/pip-build-env-4aog311c/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-4aog311c/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-4aog311c/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 496, in __init__
          _Distribution.__init__(
        File "/tmp/pip-build-env-4aog311c/overlay/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 283, in __init__
          self.finalize_options()
        File "/tmp/pip-build-env-4aog311c/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 935, in finalize_options
          ep(self)
        File "/tmp/pip-build-env-4aog311c/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 955, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/tmp/pip-build-env-4aog311c/normal/lib64/python3.9/site-packages/cffi/setuptools_ext.py", line 219, in cffi_modules
          add_cffi_module(dist, cffi_module)
        File "/tmp/pip-build-env-4aog311c/normal/lib64/python3.9/site-packages/cffi/setuptools_ext.py", line 49, in add_cffi_module
          execfile(build_file_name, mod_vars)
        File "/tmp/pip-build-env-4aog311c/normal/lib64/python3.9/site-packages/cffi/setuptools_ext.py", line 25, in execfile
          exec(code, glob, glob)
        File "scripts/libtss2_build.py", line 13, in <module>
          raise RuntimeError("Require tss2-esapi to be installed and at least version 2.4.0")
      RuntimeError: Require tss2-esapi to be installed and at least version 2.4.0
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.`

**Comment by rutujakawade** [comment]
> https://tpm2-pytss.readthedocs.io/en/latest/install.html

dnf install tpm2-tss-devel

No match for argument: tpm2-tss-devel
Error: Unable to find a match: tpm2-tss-devel

**Comment by asm3344** [comment]
any idea in how to solve this problem? 

I am facing it and I installed the dependences as mentioned here : https://tpm2-pytss.readthedocs.io/en/latest/install.html

**Comment by whooo** [comment]
@asm3344, if you run `pkg-config --modversion tss2-esys` what is the output?

**Comment by whooo** [comment]
No response, so closing for now.
