### ISSUE TITLE
ImportError: undefined symbol: Tss2_MU_TPML_TAGGED_POLICY_Unmarshal

### ISSUE THREAD

**Issue by vipindas1984** [tpm2-software/tpm2-pytss#517]
Hi All, 
I am working on a python project where I need to use tpm2-pytss library to interact with security module(OPTIGA TPM 9673 RPI EVAL) on RPi. Can anyone tell me what could be the possible problem. Some discussion mentioned the cause due to version mismatch but I didn't understand where the version mismatch happened or with which library. Can someone tell which version I should checkout to resolve this problem?

Info on versions:
tpm2-tss: 3.2.2
tpm2-tools: 5.5
tpm2-tss-engine: 1.2.0
tpm2-pytss: 2.1.0

Linux Pi kernel version: Linux pi 6.1.10-v7l+ #1628 SMP Mon Feb  6 19:20:27 GMT 2023 armv7l GNU/Linux

I have noticed similar issue was reported earlier(not in this project) but so far not addressed. https://github.com/joholl/tpm2-gui/issues/5

I followed the below GitHub page for setup the TPM: https://github.com/wxleong/tpm2-rpi4/tree/c8bca3431c3abeb0d736dd4465a8462be014adaf#install-tpm2-tss

But I am getting following error:
`pi@pi:~/vade-rpi-prj $ python3 vade-rpi-main.py 
Traceback (most recent call last):
  File "/home/pi/vade-rpi-prj/vade-rpi-main.py", line 10, in <module>
    from tpm2_pytss import tpm2
  File "/home/pi/.local/lib/python3.9/site-packages/tpm2_pytss/__init__.py", line 2, in <module>
    from .ESAPI import ESAPI
  File "/home/pi/.local/lib/python3.9/site-packages/tpm2_pytss/ESAPI.py", line 2, in <module>
    from .types import *
  File "/home/pi/.local/lib/python3.9/site-packages/tpm2_pytss/types.py", line 12, in <module>
    from ._libtpm2_pytss import ffi, lib
ImportError: /home/pi/.local/lib/python3.9/site-packages/tpm2_pytss/_libtpm2_pytss.abi3.so: undefined symbol: Tss2_MU_TPML_TAGGED_POLICY_Unmarshal`

**Comment by vipindas1984** [comment]
Duplicate.
