### ISSUE TITLE
GetRandom example produces error, but test works

### ISSUE THREAD

**Issue by PhoenixFlare7** [tpm2-software/tpm2-pytss#52]
Hi there, sorry if this is a dumb question, I am quite new to working with TPMs. I followed all of the setup instructions and I can run 
`python3 setup.py test`
with no problems.

However, if I run 
`python3 fapi_get_random.py 8`
I get the following error:
`Traceback (most recent call last):
  File "examples/fapi_get_random.py", line 59, in <module>
    main()
  File "examples/fapi_get_random.py", line 48, in main
    x = fapi_ctx.GetRandom(length)
  File "/home/pi/.local/lib/python3.7/site-packages/tpm2_pytss/context.py", line 78, in wrapper
    return custom_wrap(func)(self.ctxp, *args, **kwds)
  File "/home/pi/.local/lib/python3.7/site-packages/tpm2_pytss/context.py", line 112, in wrapper
    result = func(self, *args, **kwds)
  File "/home/pi/.local/lib/python3.7/site-packages/tpm2_pytss/util/swig.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/tpm2_pytss/exceptions.py", line 48, in wrapper
    rc = func(*args, **kwargs)
TypeError: Fapi_GetRandom() missing 1 required positional argument: 'data'`

I tried adding a "data=[]" and I get
`Traceback (most recent call last):
  File "examples/fapi_get_random.py", line 59, in <module>
    main()
  File "examples/fapi_get_random.py", line 48, in main
    x = fapi_ctx.GetRandom(length, data)
  File "/home/pi/.local/lib/python3.7/site-packages/tpm2_pytss/context.py", line 78, in wrapper
    return custom_wrap(func)(self.ctxp, *args, **kwds)
  File "/home/pi/.local/lib/python3.7/site-packages/tpm2_pytss/context.py", line 112, in wrapper
    result = func(self, *args, **kwds)
  File "/home/pi/.local/lib/python3.7/site-packages/tpm2_pytss/util/swig.py", line 173, in wrapper
    return func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/tpm2_pytss/exceptions.py", line 48, in wrapper
    rc = func(*args, **kwargs)
  File "/home/pi/.local/lib/python3.7/site-packages/tpm2_pytss/fapi_binding.py", line 14865, in Fapi_GetRandom
    return _fapi_binding.Fapi_GetRandom(context, numBytes, data)
TypeError: in method 'Fapi_GetRandom', argument 3 of type 'uint8_t **'`

Is there something I'm missing when running the example vs running the tests?

Thanks

**Comment by williamcroberts** [comment]
We just switched to CFFI, we don't have the FAPI bindings for them yet, but @joholl should be porting them over soon.
