### ISSUE TITLE
Build fails on i686 (Fedora)

### ISSUE THREAD

**Issue by Jakuje** [tpm2-software/tpm2-pytss#532]
I initially skipped the build when updating the package, but it turns out there is a demand for the package as it is used for testing the swtpm and other packages recursively so I would like to resurrect the i686 build. But I am kind of lost here as it is not clear to me what and why fails and if it is upstream or Fedora issue. I am getting the following error when I try to build the i686 package:
```
$ fedpkg mockbuild  --root=fedora-38-i386
[...]
  running build_ext
  generating cffi module 'build/temp.linux-i686-cpython-311/tpm2_pytss._libtpm2_pytss.c'
  creating build/temp.linux-i686-cpython-311
  building 'tpm2_pytss._libtpm2_pytss' extension
  creating build/temp.linux-i686-cpython-311/build
  creating build/temp.linux-i686-cpython-311/build/temp.linux-i686-cpython-311
  gcc -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -fstack-protector-strong -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fPIC -I/usr/include -I/usr/include/tss2 -I/usr/include/json-c -I/usr/include/uuid -I/usr/include/tss -I/usr/include/python3.11 -c build/temp.linux-i686-cpython-311/tpm2_pytss._libtpm2_pytss.c -o build/temp.linux-i686-cpython-311/build/temp.linux-i686-cpython-311/tpm2_pytss._libtpm2_pytss.o
  gcc -shared -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -Wl,--build-id=sha1 -g -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -Wl,--build-id=sha1 -g -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -Wl,--build-id=sha1 -specs=/usr/lib/rpm/redhat/redhat-package-notes -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m32 -march=i686 -mtune=generic -msse2 -mfpmath=sse -mstackrealign -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection build/temp.linux-i686-cpython-311/build/temp.linux-i686-cpython-311/tpm2_pytss._libtpm2_pytss.o -L/usr/lib -ltss2-esys -ltss2-tctildr -ltss2-rc -ltss2-mu -ltss2-fapi -ltss2-policy -ltss2-tcti-spi-helper -o build/lib.linux-i686-cpython-311/tpm2_pytss/_libtpm2_pytss.abi3.so
  Traceback (most recent call last):
    File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
      main()
    File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 412, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 397, in _build_with_temp_dir
      self.run_setup()
    File "/usr/lib/python3.11/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 280, in <module>
    File "/usr/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 968, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 325, in run
      self.run_command("build")
    File "/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.11/site-packages/setuptools/_distutils/command/build.py", line 132, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.11/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/usr/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 987, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.11/site-packages/cffi/setuptools_ext.py", line 144, in run
      base_class.run(self)
    File "<string>", line 230, in run
    File "<string>", line 210, in get_mappings
    File "/usr/lib/python3.11/site-packages/pycparser/c_parser.py", line 149, in parse
      return self.cparser.parse(
             ^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/ply/yacc.py", line 333, in parse
      return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/ply/yacc.py", line 1201, in parseopt_notrack
      tok = call_errorfunc(self.errorfunc, errtoken, self)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/ply/yacc.py", line 192, in call_errorfunc
      r = errorfunc(token)
          ^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/site-packages/pycparser/c_parser.py", line 1858, in p_error
      self._parse_error(
    File "/usr/lib/python3.11/site-packages/pycparser/plyparser.py", line 67, in _parse_error
      raise ParseError("%s: %s" % (coord, msg))
  pycparser.plyparser.ParseError: /usr/lib/gcc/i686-redhat-linux/13/include/stddef.h:434:3: before: __float128
  error: subprocess-exited-with-error
  
  × Building wheel for tpm2-pytss (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /usr/bin/python3 /usr/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /builddir/build/BUILD/tpm2-pytss-2.1.0/.pyproject-builddir/tmph854zznf
  cwd: /builddir/build/BUILD/tpm2-pytss-2.1.0
  Building wheel for tpm2-pytss (pyproject.toml): finished with status 'error'
  ERROR: Failed building wheel for tpm2-pytss
Failed to build tpm2-pytss
ERROR: Failed to build one or more wheels
```
builds of all the other architectures work ok.

The important line is probably the following line:
```
  pycparser.plyparser.ParseError: /usr/lib/gcc/i686-redhat-linux/13/include/stddef.h:434:3: before: __float128
```
The part of the header file contains (with line 434 being the one after `ifdef __i386__`:
```
typedef struct {
  long long __max_align_ll __attribute__((__aligned__(__alignof__(long long))));
  long double __max_align_ld __attribute__((__aligned__(__alignof__(long double))));
  /* _Float128 is defined as a basic type, so max_align_t must be
     sufficiently aligned for it.  This code must work in C++, so we
     use __float128 here; that is only available on some
     architectures, but only on i386 is extra alignment needed for
     __float128.  */
#ifdef __i386__
  __float128 __max_align_f128 __attribute__((__aligned__(__alignof(__float128))));
#endif
} max_align_t;
```
On first sight, I do not see any issue with the above struct.

This file is in Fedora provided by `gcc-13.2.1-1.fc38.i686` (same for latest Fedora 40 with Python3.12).

Do you have as part of a CI builds on a 32b architecture? Is it issue only in Fedora or also elsewhere?

**Comment by whooo** [comment]
Try with https://github.com/tpm2-software/tpm2-pytss/commit/916c47ef6c30c2c6688f207bb780a2f4e6ef5384 applied, it will be in the next release

**Comment by Jakuje** [comment]
Thanks for the prompt reply! I missed that commit when going through the history! Indeed, that solves the build problems!
