### ISSUE TITLE
Attestation Quote and sending Public AK and EK to remote server

### ISSUE THREAD

**Issue by aliahad97** [tpm2-software/tpm2-pytss#555]
Hello,

I am trying to make a toy example for TPM attestation (code attached below) but am having some issues. 

1. I can't seem to figure out how to save or load `ak_public` and `ek_public`. Essentially, I will be sending the keys to server eventually, and want to understand what would be the code for it. I tried using `to_pem` and `TPM2B_PUBLIC.from_pem` (e.g., `ak_public.to_pem()` and write to file, then read the file and use `TPM2B_PUBLIC.from_pem('ak_pub.pem', symmetric="aes128cfb")`) but `activate_credential` fails. What is the correct way of doing this?

2. The code below throws an error when at `quote` function. Is there something I am missing?

Thanks!
Ali

## Code: 

```python

def low_ek_session(ectx: ESAPI):
    session = ectx.start_auth_session(
        tpm_key=ESYS_TR.NONE,
        bind=ESYS_TR.NONE,
        session_type=TPM2_SE.POLICY,
        symmetric=TPMT_SYM_DEF(algorithm=TPM2_ALG.NULL),
        auth_hash=TPM2_ALG.SHA256,
    )
    ectx.policy_secret(ESYS_TR.ENDORSEMENT, session, b"", b"", b"", 0)
    return session


with ESAPI(tcti="mssim:host=localhost,port=2321") as ectx:
    # Load EK and EK cert.
    ## EK only
    nv_read = NVReadEK(ectx)
    cert_bytes, ec_template = create_ek_template("EK-RSA2048", nv_read)
    ### Check if cert retrieved
    if cert_bytes:
        cert = load_der_x509_certificate(cert_bytes)
    else:
        cert = None
    ek_handle, ek_pub_temp, _, _, _ = ectx.create_primary(
        TPM2B_SENSITIVE_CREATE(), ec_template, ESYS_TR.ENDORSEMENT
    )

    # Create and load AK.
    session = low_ek_session(ectx)
    private, ak_public, creation_data, digest, creation = ectx.create(
        ek_handle, None, in_public="ecc256", session1=session
    )
    session = low_ek_session(ectx)
    ak_handle = ectx.load(ek_handle, private, ak_public, session1=session)

    # Load the public key from the certificate, so the server side only needs to receive the certificate.
    if cert:
        ek_public = TPM2B_PUBLIC.from_pem(
            cert.public_bytes(encoding=serialization.Encoding.DER),
            symmetric="aes128cfb",
        )
    else:
        ek_public = TPM2B_PUBLIC.from_pem(ek_pub_temp.to_pem(), symmetric="aes128cfb")
        # TODO: How to copy ak_public and ek_pub
        # ak_public_new = TPM2B_PUBLIC.unmarshal(ak_public.marshal())

    # -------------------- REMOTE Verifier ---------------
    '''
    Expects: ek_public and ak_public
    '''
    print(ak_public.get_name(), ak_public.get_name())
    id_object, encrypted_secret = make_credential(
        ek_public, b"dankjewel!", ak_public.get_name()
    )
    # -------------------- Local Verifier ---------------
    '''
    Expects: id_object and encrypted secret
    '''
    session = low_ek_session(ectx)
    decrypted_digest = ectx.activate_credential(
        ak_handle, ek_handle, id_object, encrypted_secret, session2=session
    )
    # -------------------- REMOTE Verifier ---------------
    '''
    Expects: decrypted_digest
    '''
    print(str(bytes(decrypted_digest)))
    pcrsels = TPML_PCR_SELECTION.parse("sha256:0,2,4,8+sha1:all")
    extradata_to_use = TPM2B_DATA(bytes(decrypted_digest)) # NONCE
    # -------------------- Local Verifier ---------------
    '''
    Expects: quote pcr-sel , nonce <extra data to use>
    '''
    # TODO: Complete pcr_quote -> Fix this!!
    # TPM2B_DATA(extradata_to_use)
    quote,signature = ectx.quote(ak_handle, pcrsels, extradata_to_use)
    # -------------------- REMOTE Verifier ---------------
    '''
    Expects: quote, signature
    '''
    att,_ = TPMS_ATTEST.unmarshal( bytes(quote) )
    print("att=",att)
    # Cleanup
    ectx.flush_context(ek_handle)
    ectx.flush_context(ak_handle)
    ectx.flush_context(session)
```

## Output:
```
WARNING:esys:src/tss2-esys/api/Esys_NV_ReadPublic.c:309:Esys_NV_ReadPublic_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/esys_tr.c:243:Esys_TR_FromTPMPublic_Finish() Error NV_ReadPublic ErrorCode (0x0000018b) 
ERROR:esys:src/tss2-esys/esys_tr.c:398:Esys_TR_FromTPMPublic() Error TR FromTPMPublic ErrorCode (0x0000018b) 
WARNING:esys:src/tss2-esys/api/Esys_NV_ReadPublic.c:309:Esys_NV_ReadPublic_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/esys_tr.c:243:Esys_TR_FromTPMPublic_Finish() Error NV_ReadPublic ErrorCode (0x0000018b) 
ERROR:esys:src/tss2-esys/esys_tr.c:398:Esys_TR_FromTPMPublic() Error TR FromTPMPublic ErrorCode (0x0000018b) 
WARNING:esys:src/tss2-esys/api/Esys_NV_ReadPublic.c:309:Esys_NV_ReadPublic_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/esys_tr.c:243:Esys_TR_FromTPMPublic_Finish() Error NV_ReadPublic ErrorCode (0x0000018b) 
ERROR:esys:src/tss2-esys/esys_tr.c:398:Esys_TR_FromTPMPublic() Error TR FromTPMPublic ErrorCode (0x0000018b) 
000bde83eb982c88bba721a9ff00f798bdfa710c09fa1dda5538c44a1a284a4679bd 000bde83eb982c88bba721a9ff00f798bdfa710c09fa1dda5538c44a1a284a4679bd
b'dankjewel!'
WARNING:esys:src/tss2-esys/api/Esys_Quote.c:317:Esys_Quote_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_Quote.c:105:Esys_Quote() Esys Finish ErrorCode (0x000002d2) 
Traceback (most recent call last):
  File "/home/aahad/py-tpm/experiment/main.py", line 101, in <module>
    quote,signature = ectx.quote(ak_handle, pcrsels, extradata_to_use)
  File "/home/aahad/py-tpm/tpm2-pytss/src/tpm2_pytss/ESAPI.py", line 2914, in quote
    _chkrc(
  File "/home/aahad/py-tpm/tpm2-pytss/src/tpm2_pytss/internal/utils.py", line 176, in _chkrc
    raise TSS2_Exception(rc)
tpm2_pytss.TSS2_Exception.TSS2_Exception: tpm:parameter(2):unsupported or incompatible scheme
```

**Comment by whooo** [comment]
I suspect that your AK doesn't have any signature scheme set (it's off by default when just using "ecc256").
Doing something like the following might work:
```python
ak_template = TPM2B_PUBLIC.parse(
    "ecc256:ecdsa",
    objectAttributes=TPMA_OBJECT.DEFAULT_TPM2_TOOLS_CREATE_ATTRS ^ TPMA_OBJECT.DECRYPT
)
private, ak_public, creation_data, digest, creation = ectx.create(
    ek_handle, None, in_public=ak_template, session1=session
)
```

**Comment by aliahad97** [comment]
Thank you @whooo! This worked! Appreciate the help!

**Comment by aliahad97** [comment]
Any idea how to copy keys to and from server? Specifically for `ak_public`? I have done something below but the `ak_public_remote` is giving issues:

```python
    open('ek_public.pem', 'wb').write(ek_public.to_pem())
    open('ak_public.pem', 'wb').write(ak_public.to_pem())
    # -------------------- REMOTE Verifier ---------------
    '''
    Expects: ek_public and ak_public
    '''
    ak_public_remote = TPM2B_PUBLIC.from_pem(open("ak_public.pem", 'rb').read(), symmetric="aes128cfb")
    ek_public_remote = TPM2B_PUBLIC.from_pem(open("ek_public.pem", 'rb').read(), symmetric="aes128cfb")
    print("AK Names:", ak_public.get_name(), ak_public_remote.get_name())
    id_object, encrypted_secret = make_credential(
        ek_public_remote, b"dankjewel!", ak_public_remote.get_name()
    )
    # -------------------- Local Verifier ---------------
    '''
    Expects: id_object and encrypted secret
    '''
    session = low_ek_session(ectx)
    decrypted_digest = ectx.activate_credential(
        ak_handle, ek_handle, id_object, encrypted_secret, session2=session
    )
```

Getting the following error:
```
AK Names: 000be0dbd185275c8f19a0b35a2ca3b35e838c6b6ad2774d538dd686fac6466b11e3 000b5c9b82ed8f36f67bd2db5b77b4706546db543eb902fbd79df0ccba415d1b4e81
WARNING:esys:src/tss2-esys/api/Esys_ActivateCredential.c:321:Esys_ActivateCredential_Finish() Received TPM Error 
ERROR:esys:src/tss2-esys/api/Esys_ActivateCredential.c:105:Esys_ActivateCredential() Esys Finish ErrorCode (0x000001df) 
Traceback (most recent call last):
  File "/home/aahad/py-tpm/experiment/main.py", line 94, in <module>
    decrypted_digest = ectx.activate_credential(
  File "/home/aahad/py-tpm/tpm2-pytss/src/tpm2_pytss/ESAPI.py", line 1034, in activate_credential
    _chkrc(
  File "/home/aahad/py-tpm/tpm2-pytss/src/tpm2_pytss/internal/utils.py", line 176, in _chkrc
    raise TSS2_Exception(rc)
tpm2_pytss.TSS2_Exception.TSS2_Exception: tpm:parameter(1):integrity check failed
```

**Comment by whooo** [comment]
Converting to PEM looses metadata, you can use the marshal/unmarshal methods on the type.
```python
# sending side
ak_bytes = ak_public.marshal()
# recv side
ak_public, _ = TPM2B_PUBLIC.unmarshal(ak_bytes)
```

**Comment by aliahad97** [comment]
Ohh that makes sense. 

Thank you! That worked! Really appreciate it!
