### ISSUE TITLE
Example of importing external key

### ISSUE THREAD

**Issue by salrashid123** [tpm2-software/tpm2-pytss#596]
I'm trying to import an external RSA key into the TPM but can't pinpoint how to do it.

I've tried something like the following where the `import_data` is just the raw RSA PEM key (similar to how the public key is imported.  I also noticed this in [Fapi_Import.c](https://github.com/tpm2-software/tpm2-tss/blob/master/src/tss2-fapi/api/Fapi_Import.c#L225) bit which seems to allow parsing of the PEM private.

any pointers would be appreciated

```python
from tpm2_pytss import *

FAPIConfig(profile_name='P_RSA2048SHA256',tcti="swtpm:port=2321")

fapi_ctx = FAPI()
fapi_ctx.provision()

path = f"/HS/SRK/api_key"
key_private_pem="-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANB.....HKdILIsosfY8wA==\n-----END PRIVATE KEY-----\n"

fapi_ctx.import_object(path=path, import_data=key_private_pem)
```

```
	tpm2_createprimary -C o -g sha256 -G rsa -c primary.ctx
	tpm2_import -C primary.ctx -G rsa -i private.pem -u key.pub -r key.prv
	tpm2_load -C primary.ctx -u key.pub -r key.prv -c key.ctx
	tpm2_evictcontrol -C o -c key.ctx 0x81010002
```

**Comment by whooo** [comment]
What kind of error do you get? Which version of tpm2-tss do you use with tpm2-pytss?

**Comment by salrashid123** [comment]
i'm seeing the following (`Invalid ImportData`) i think from [here](https://github.com/tpm2-software/tpm2-tss/blob/f5ee2b67e1c2cdaa2ab0fc25e1ed2f74a611f8e6/src/tss2-fapi/api/Fapi_Import.c#L287)

```bash
$ python3 fapi_import_sign.py 
WARNING:fapi:src/tss2-fapi/ifapi_io.c:339:ifapi_io_check_create_dir() Directory /home/srashid/.local/share/tpm2-tss/user/keystore/ does not exist, creating 
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:246:Fapi_Provision_Async() ErrorCode (0x00060035) Profile P_RSA2048SHA256 was already provisioned. 
ERROR:fapi:src/tss2-fapi/api/Fapi_Provision.c:157:Fapi_Provision() ErrorCode (0x00060035) Provision 
ERROR:fapi:src/tss2-fapi/api/Fapi_Import.c:228:Fapi_Import_Async() ErrorCode (0x0006000b) Invalid importData. 
ERROR:fapi:src/tss2-fapi/api/Fapi_Import.c:84:Fapi_Import() ErrorCode (0x0006000b) Entity_Import 
Traceback (most recent call last):
  File "/home/srashid/Desktop/pytss/fapi_import_sign.py", line 13, in <module>
    fapi_ctx.import_object(path=path, import_data=key_private_pem)
  File "/home/srashid/Desktop/pytss/env/lib/python3.11/site-packages/tpm2_pytss/FAPI.py", line 629, in import_object
    _chkrc(
  File "/home/srashid/Desktop/pytss/env/lib/python3.11/site-packages/tpm2_pytss/internal/utils.py", line 176, in _chkrc
    raise TSS2_Exception(rc)
tpm2_pytss.TSS2_Exception.TSS2_Exception: fapi:A parameter has a bad value
```


with ` libtss2-dev  (4.0.1-7.2)` and 

```bash
$ python3 -m pip install tpm2-pytss
Requirement already satisfied: tpm2-pytss in ./env/lib/python3.11/site-packages (2.3.0)
Requirement already satisfied: cffi>=1.0.0 in ./env/lib/python3.11/site-packages (from tpm2-pytss) (1.17.0)
Requirement already satisfied: asn1crypto in ./env/lib/python3.11/site-packages (from tpm2-pytss) (1.5.1)
Requirement already satisfied: cryptography>=3.0 in ./env/lib/python3.11/site-packages (from tpm2-pytss) (43.0.0)
Requirement already satisfied: packaging in ./env/lib/python3.11/site-packages (from tpm2-pytss) (24.1)
Requirement already satisfied: pyyaml in ./env/lib/python3.11/site-packages (from tpm2-pytss) (6.0.2)
Requirement already satisfied: pycparser in ./env/lib/python3.11/site-packages (from cffi>=1.0.0->tpm2-pytss) (2.22)
```

**Comment by whooo** [comment]
It looks like the support for PEM encoded private keys was added in tpm2-tss 4.1.0 which would explain this issue.

**Comment by whooo** [comment]
I'm not to familiar with FAPI, but you might be able to use the JSON encoder in tpm2-pytss to generate a JSON document that fapi import will accept
