### ISSUE TITLE
Issues with context.quote() 

### ISSUE THREAD

**Issue by tsarovekAN** [tpm2-software/tpm2-pytss#606]
I'm having a consistent error on `.quote()` function. My setup consists of:
- tpm_server by ibm as tpm emulator
- Python 3.12.1 with Flask as endpoint service
- pytss 2.2.0 directly from this git
- and all the other necessary background like tpm2_tools, *_tss and etc.

The error I receive from FAPI:
```
WARNING:esys:src/tss2-esys/api/Esys_Load.c:324:Esys_Load_Finish() Received TPM Error 
ERROR:fapi:src/tss2-fapi/fapi_util.c:1996:ifapi_load_key_finish() ErrorCode (0x000001df) Load 
ERROR:fapi:src/tss2-fapi/fapi_util.c:1780:ifapi_load_keys_finish() Load keys ErrorCode (0x000001df) 
ERROR:fapi:src/tss2-fapi/api/Fapi_Quote.c:362:Fapi_Quote_Finish() ErrorCode (0x000001df)  Load key. 
ERROR:fapi:src/tss2-fapi/api/Fapi_Quote.c:134:Fapi_Quote() ErrorCode (0x000001df) PCR_Quote 
```

The error I receive from pytss:
```
Traceback (most recent call last):
  File "/opt/tpm_integration/c_interface/tpm_attestation.py", line 133, in receive_context_quote
    quote = tpm_context.quote(
            ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib64/python3.12/site-packages/tpm2_pytss/FAPI.py", line 1055, in quote
    _chkrc(ret)
  File "/usr/local/lib64/python3.12/site-packages/tpm2_pytss/internal/utils.py", line 176, in _chkrc
    raise TSS2_Exception(rc)
tpm2_pytss.TSS2_Exception.TSS2_Exception: tpm:parameter(1):integrity check failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tpm_integration/api/attest.py", line 29, in attest_by_quote
    explicit_attestation: str = receive_explicit_attestation(nonce, [0,1,2,3,4])
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tpm_integration/service/attestator.py", line 211, in receive_explicit_attestation
    quote_information: Tuple[str, str] = receive_context_quote(nonce, pcr_list)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/tpm_integration/c_interface/tpm_attestation.py", line 144, in receive_context_quote
    raise ValueError(f'Receiving Quote failed: {e}')
```

My code:
```
def receive_context_quote(nonce: bytes, pcr_list: List[int]) -> Tuple[str, str]:
    """
    
    """
    tpm_context: FAPI = local_storage.get_context()
    attestation_key_path = local_storage.get_AK_path()

    try:
        print(check_key_exists(tpm_context, attestation_key_path))
        quote = tpm_context.quote(
            path=attestation_key_path, 
            pcrs=pcr_list, 
            #qualifying_data=nonce.hex()
        )
        quote_json = json.loads(quote)
        attestation_data = quote_json["attestation"]
        signature = quote_json["signature"]
        return (attestation_data, signature)

    except Exception as e:
        raise ValueError(f'Receiving Quote failed: {e}')
        
def check_key_exists(tpm_context: FAPI, key_path: str) -> bool:
    """
    Function that checks whether a key path exists or not.

    == Params ==
    tpm_context: FAPI - context of a tpm
    key_path: str - path to the key that needs to be checked

    == Returns ==
    bool - True if key exists, False if not
    """
    try:
        tpm_context.get_tpm_blobs(path=key_path)
        return True
    except:
        return False
```

Used parameters:
- ak_path: '/HS/SRK/test'
- test_pcr_list: [0,1,2,3,4]
- test_nonce: os.urandom(32) (if it's relevant)

I'd appreciate any help

**Comment by whooo** [comment]
According to tpm2_rc_decode the error code says "tpm:parameter(1):integrity check failed", so I suspect that the key hierarchie seed has changed, has the state of the simulator been reset after creating the key you try to use with quote?
Could you try creating the key just before running quote?

**Comment by tsarovekAN** [comment]
I guess, I didn't reset keystore after a restart. Thank you for the hint. I didn't think of that at all, I was sure I did...
If anyone is looking for lazy reset script, here's my reset_keystore.sh xD
```
#!/bin/bash
set -e

rm -rf /usr/local/var/lib/tpm2-tss/system/keystore/*
```
