### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by andyghw** [tpm2-software/tpm2-pytss#72]
Hi, I am new with tpm2-pytss. I have a Raspberry pi with a TPM2.0 chip with it and I am able to run all the TPM2.0 commands by using the IBM library https://sourceforge.net/p/ibmtpm20tss/tss/ci/master/tree/demo/. But after I installed tpm2-pytss on it and tried running the GET_RANDOM test, it always give me the PERMISSION_ERROR like below:
```
Traceback (most recent call last):
  File "test_py3.py", line 58, in <module>
    main()
  File "test_py3.py", line 26, in main
    simulator = ctx_stack.enter_context(Simulator())
  File "/usr/lib/python3.5/contextlib.py", line 307, in enter_context
    result = _cm_type.__enter__(cm)
  File "/home/pi/.local/lib/python3.5/site-packages/tpm2_pytss/util/simulator.py", line 128, in __enter__
    self.start()
  File "/home/pi/.local/lib/python3.5/site-packages/tpm2_pytss/util/simulator.py", line 101, in start
    stderr=subprocess.PIPE,
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
PermissionError: [Errno 13] Permission denied
```
test_py3.py
```
import sys
import random
import tempfile
import contextlib

from tpm2_pytss.fapi import FAPI, FAPIDefaultConfig
from tpm2_pytss.binding import *
from tpm2_pytss.util.simulator import Simulator


def main():
    # Usage information
    if len(sys.argv) != 2:
        print("Ouput N random bytes to stdout", file=sys.stderr)
        print("", file=sys.stderr)
        print("Usage: {sys.argv[0]} length(between 8 and 32)", file=sys.stderr)
        sys.exit(1)
    # Number of random bytes to get (between 8 and 32)
    length = int(sys.argv[1])
    # Input validation
    if length < 8 or length > 32:
        raise ValueError("length must be between 8 and 32")
    # Create a context stack
    with contextlib.ExitStack() as ctx_stack:
        # Create a simulator
        simulator = ctx_stack.enter_context(Simulator())
        # Create temporary directories to separate this example's state
        user_dir = ctx_stack.enter_context(tempfile.TemporaryDirectory())
        log_dir = ctx_stack.enter_context(tempfile.TemporaryDirectory())
        system_dir = ctx_stack.enter_context(tempfile.TemporaryDirectory())
        # Create the FAPI object
        fapi = FAPI(
            FAPIDefaultConfig._replace(
                user_dir=user_dir,
                system_dir=system_dir,
                log_dir=log_dir,
                tcti="mssim:port=%d" % (simulator.port,),
                tcti_retry=100,
                ek_cert_less=1,
            )
        )
        # Enter the context, create TCTI connection
        fapi_ctx = ctx_stack.enter_context(fapi)
        # Call Fapi_Provision
        fapi_ctx.Provision(None, None, None)
        # Create a pointer to the byte array we'll get back from GetRandom
        array = ctx_stack.enter_context(UINT8_PTR_PTR())
        # Call GetRandom and convert the resulting array to a Python bytearray
        value = to_bytearray(length, fapi_ctx.GetRandom(length, array))
        # Ensure we got the correct number of bytes
        if length != len(value):
            raise AssertionError("Requested %d bytes, got %d" % (length, len(value)))
        # Print bytes to stdout
        sys.stdout.buffer.write(value)


if __name__ == "__main__":
    main()
```

I did copy the latest tmp_server to my $path, which is `/usr/local/bin`

Do you have any clues about it?

Thanks,
Iven

**Comment by andyghw** [comment]
Never mind, put the wrong tpm-server file
